site_name: "Edgar Alcaraz Caballer - 1r ASIX"
custom_dir: docs/images
theme:
  name: material
  palette:
    scheme: slate  
    primary: 'indigo'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Fira Code'

nav:
  - Inicio: index.md
  - 1. Sistema operatiu: sistema-operatiu.md
  - 2. Punts de restauració: punts-restauracio.md
  - 3. Llicenciament: llicenciament.md
  - 4. Gestors d’arrancada: gestors-arrancada.md
  - 5. Configuració xarxa bàsica: configuracio-xarxa-basica.md
  - 6. Comandes generals: comandes-generals.md
  - 7. Instal·lacions de programari: instal-lacions-programari.md

plugins:
  - search

copyright: <p xmlns:cc="http://creativecommons.org/ns" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://edgaralca8.github.io/MKdocs_Edgar_Alcaraz/">Edgar Alcaraz pagina web</a> by <span property="cc:attributionName">Edgar Alcaraz</span> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>